#!/usr/bin/env bash
# A worker that publishes backlight status based on udev events

BL_DIR=/sys/class/backlight/$BL_DEV
BNESS_FILE=$BL_DIR/actual_brightness
BNESS_MAX_FILE=$BL_DIR/max_brightness
POWER_FILE=$BL_DIR/bl_power

while :; do
  bness=$(<"$BNESS_FILE")
  bness_max=$(<"$BNESS_MAX_FILE")
  power=$(<"$POWER_FILE")
  printf 'bl_bness=%s\nbl_bness_max=%s\nbl_power=%s\n' "$bness" "$bness_max" \
    "$power"
  read -r # Wait for next event
done < <(stdbuf -oL udevadm monitor -k -s backlight |
  stdbuf -oL sed -n '/^KERNEL\[/p')
