#!/usr/bin/env bash
# A worker that publishes WiFi status as reported by iw

hash iw stdbuf

declare -A last_vars vars
while :; do
  while IFS='=' read -r key val; do
    vars[$key]=$val
  done < <(
    iw dev "$WIFI_DEV" link |
      stdbuf -oL sed -n 's/.*SSID: \(.\+\)/wifi_ssid=\1/p;'\
's/.*signal: \(-\?[0-9]\+\) dBm/wifi_dbm=\1/p;'\
's/Not connected./wifi_ssid=\nwifi_dbm=/p'
    )

  for key in "${!vars[@]}"; do
    val=${vars[$key]}
    if [ ! "$val" = "${last_vars[$key]}" ]; then
      printf '%s=%s\n' "$key" "$val"
      last_vars[$key]=$val
    fi
  done

  read -r -t 5 # Sleep
done
