#!/bin/sh
# Run unixbar out of the local directory.

# Put this directory in PYTHONPATH for relative module lookup.
SELF=$(readlink -f "$0")
SELFDIR=$(dirname "$SELF")
export PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}$SELFDIR"

exec python3.5 -m unixbar
